# PyTorch Basics: Gradients and Tensors

## Importing the Libraries

In [3]:
import torch

## Working with Tensors

In [4]:
# Creating a Number
t1 = torch.tensor(4.)
t1

tensor(4.)

In [6]:
t1.dtype

torch.float32

In [7]:
# Creating a Vector
t2 = torch.tensor([1., 2., 3., 4.])
t2

tensor([1., 2., 3., 4.])

In [9]:
# Creating a Matrix
t3 = torch.tensor([[1., 2.], 
                   [3., 4.],
                   [5., 6.]])
t3

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [10]:
# Creating a 3D array
t4 = torch.tensor([[[1.,2.], 
                    [3.,4.]]])
t4

tensor([[[1., 2.],
         [3., 4.]]])

## Getting the Shape of the Tensor

In [11]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [12]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [13]:
print(t3)
t3.shape

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


torch.Size([3, 2])

In [14]:
print(t4)
t4.shape

tensor([[[1., 2.],
         [3., 4.]]])


torch.Size([1, 2, 2])

## Tensor Operations and Gradients

In [16]:
# We can create symbolic graphs using variables using the requires_grad command
x = torch.tensor(3.)
w = torch.tensor(4.0, requires_grad = True)
b = torch.tensor(5.0, requires_grad = True)

In [18]:
# Arithmatic Operations
y = w*x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [20]:
# Compute the derivatives
y.backward()

# Display Gradients (Note that: The derivatives of y with respect to the input tensors are stored in the 
# .grad property of the respective tensors. )
print('dy/dx', x.grad)
print('dy/dw', w.grad)
print('dy/db', b.grad)

dy/dx None
dy/dw tensor(3.)
dy/db tensor(1.)


## Tensor Functions

In [22]:
# Create a tensor with a fixed value for every element
t6 = torch.full((3,2), 42)
t6

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [23]:
t7 = torch.cat((t3, t6))
t7

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])

In [24]:
# Computing the sin of each element
t8 = torch.sin(t7)
t8

tensor([[ 0.8415,  0.9093],
        [ 0.1411, -0.7568],
        [-0.9589, -0.2794],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

In [25]:
# Reshaping the tensor
t9 = t8.reshape(3, 2, 2)
t9

tensor([[[ 0.8415,  0.9093],
         [ 0.1411, -0.7568]],

        [[-0.9589, -0.2794],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])

## Interopratibility with NumPy

In [26]:
import numpy as np

x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [27]:
# convert the numpy array to a torch tensor
y = torch.from_numpy(x)
y

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [28]:
x.dtype, y.dtype

(dtype('int32'), torch.int32)

In [30]:
# Convert a torch tensor to a NumPy array
z = y.numpy()
z

array([[1, 2],
       [3, 4]])