<a href="https://colab.research.google.com/github/cekbote/pytorch-tutorials/blob/master/PyTorch_Tutorial_1_Free_Code_Camp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Tutorial 1 - Free Code Camp

In [ ]:
import torch

## Creating Tensors

In [ ]:
t1 = torch.tensor(4)
t1

tensor(4)

In [ ]:
t1.dtype

torch.int64

In [ ]:
# Vector
t2 = torch.tensor([1,2,3,4])
t2

tensor([1, 2, 3, 4])

In [ ]:
# Matrix
t3 = torch.tensor([[5, 4], 
                   [7, 8],
                   [9, 10]])
t3

tensor([[ 5,  4],
        [ 7,  8],
        [ 9, 10]])

In [ ]:
# 3-D Array
t4 = torch.tensor([[[11, 12, 13],
                    [13, 14, 15]],
                   [[15, 16, 17],
                    [18, 19, 20]]])
t4

tensor([[[11, 12, 13],
         [13, 14, 15]],

        [[15, 16, 17],
         [18, 19, 20]]])

In [ ]:
print(t1)
t1.shape

tensor(4)


torch.Size([])

In [ ]:
print(t2)
t2.shape

tensor([1, 2, 3, 4])


torch.Size([4])

In [ ]:
print(t3)
t3.shape

tensor([[ 5,  4],
        [ 7,  8],
        [ 9, 10]])


torch.Size([3, 2])

In [ ]:
print(t4)
t4.shape

tensor([[[11, 12, 13],
         [13, 14, 15]],

        [[15, 16, 17],
         [18, 19, 20]]])


torch.Size([2, 2, 3])

## Tensor Operations and Gradients

In [ ]:
# Create Tensors
# Only Tensors of floating point and complex dtype can require gradients
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [ ]:
# Arithmatic Operations
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [ ]:
# As expected, y is a tensor with the value 3 * 4 + 5 = 17. 
# What makes PyTorch special is that we can automatically compute the derivative of y w.r.t. 
# the tensors that have requires_grad set to True i.e. w and b. To compute the derivatives, 
# we can call the .backward method on our result y.

# Computing Derivatives

y.backward()

In [ ]:
# The derivates of y w.r.t the input tensors are stored in the .grad property of the respective tensors.
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


## Matrix Gradients

A good place to get the formulae for matrix and vector gradients can be found [here](https://en.wikipedia.org/wiki/Matrix_calculus#Derivatives_with_matrices)

In [ ]:
w = torch.tensor([[1., 2., 3.],
                  [3., 4., 4.],
                  [5., 6., 6.]], requires_grad=True)
x = torch.tensor([[1.], [2.], [3.]], requires_grad=True)
b = torch.tensor([[4.], [5.], [6.]], requires_grad=True)
print(w, x, b)
w.shape, x.shape, b.shape

tensor([[1., 2., 3.],
        [3., 4., 4.],
        [5., 6., 6.]], requires_grad=True) tensor([[1.],
        [2.],
        [3.]], requires_grad=True) tensor([[4.],
        [5.],
        [6.]], requires_grad=True)


(torch.Size([3, 3]), torch.Size([3, 1]), torch.Size([3, 1]))

In [ ]:
y = w * x + b
y

tensor([[ 5.,  6.,  7.],
        [11., 13., 13.],
        [21., 24., 24.]], grad_fn=<AddBackward0>)

In [ ]:
# Now if you try y.backwards, it won't work as you need a scalar output to find
# the grad. Hence we can use a trick. We basically add all the elements of y.
y = y.sum()
y.backward()

In [ ]:
print('dy/dw:', w.grad)
print('dy/dx:', x.grad)
print('dy/db:', b.grad)

dy/dw: tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.]])
dy/dx: tensor([[ 6.],
        [11.],
        [17.]])
dy/db: tensor([[3.],
        [3.],
        [3.]])


## Interoperability with Numpy

In [ ]:
import numpy as np

In [ ]:
x = np.array([[1., 2.],
              [3., 4.]])
x

array([[1., 2.],
       [3., 4.]])

In [ ]:
# Convert the NumPy array to a torch tensor
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [ ]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

In [ ]:
# Convert torch tensor to a numpy array
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])